### PR TITLE
Configure bicopter for ArduPilot

### PR DESCRIPTION
**Pull request by srmainwaring**
Add ArduPilot plugin, configure control inputs and provide an initial set of parameters.

Disable the joint control plugins in the bicopter model, as we will initially use the controllers provided in the ArduPilot plugin.

Rebase and merge after

- #2 
- #3 

### Usage

Run the Gazebo simulation:

```bash
gz sim -v4 -r bicopter_runway.sdf
```

Run ArduPilot SITL

```bash
$ sim_vehicle.py -v ArduCopter --model JSON --add-param-file=$HOME//ros_ws/src/bicopter_simulation/config/bicopter.param --console --map
```

Check params:

```console
# check frame type
MANUAL> param show FRAME_*
MANUAL> FRAME_CLASS      10
FRAME_TYPE       1

# check servos
MANUAL> SERVO1_FUNCTION  74          # ThrottleRight
SERVO1_MAX       2000
SERVO1_MIN       1000
SERVO1_REVERSED  0           # Normal
SERVO1_TRIM      1000

MANUAL> param show SERVO2_*
MANUAL> SERVO2_FUNCTION  73          # ThrottleLeft
SERVO2_MAX       2000
SERVO2_MIN       1000
SERVO2_REVERSED  0           # Normal
SERVO2_TRIM      1000

MANUAL> param show SERVO3_*
MANUAL> SERVO3_FUNCTION  76          # TiltMotorFrontRight
SERVO3_MAX       2000
SERVO3_MIN       1000
SERVO3_REVERSED  1           # Reversed
SERVO3_TRIM      1500

MANUAL> param show SERVO4_*
MANUAL> SERVO4_FUNCTION  75          # TiltMotorFrontLeft
SERVO4_MAX       2000
SERVO4_MIN       1000
SERVO4_REVERSED  0           # Normal
SERVO4_TRIM      1500
```

Motor tests

```console
# right motor (ccw)
MANUAL> motortest 1 1 1010 1

# right tilt servo (back)
MANUAL> motortest 2 1 1010 1

# left motor (cw)
MANUAL> motortest 3 1 1010 1

# left tilt servo (forward)
MANUAL> motortest 3 1 1010 1
```

https://github.com/GreenPine-CK/bicopter_simulation/assets/24916364/105e4897-d800-4e7b-a17c-325310e8072e

### CODE REVIEW

**Comment by GreenPine-CK** [comment]
```
lck@aaa:~/mav_ws/ardupilot/Tools$ python3 ../Tools/autotest/sim_vehicle.py -v ArduCopter -f JSON --add-param-file=$HOME/ros_ws/src/bicopter_simulation/config/bicopter.param --console --map
SIM_VEHICLE: Start
WARNING: no config for frame (JSON)
SIM_VEHICLE: Killing tasks
SIM_VEHICLE: Starting up at SITL location
SIM_VEHICLE: WAF build
SIM_VEHICLE: Configure waf
SIM_VEHICLE: "/home/lck/mav_ws/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl"
Setting top to                           : /home/lck/mav_ws/ardupilot 
Setting out to                           : /home/lck/mav_ws/ardupilot/build 
Autoconfiguration                        : enabled 
Checking for program 'python'            : /usr/bin/python3 
Checking for python version >= 3.6.9     : 3.8.10 
Setting board to                         : sitl 
Using toolchain                          : native 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for c flags '-MMD'              : yes 
Checking for cxx flags '-MMD'            : yes 
CXX Compiler                             : g++ 9.4.0 
Checking for need to link with librt     : not necessary 
Checking for feenableexcept              : yes 
Enabling -Werror                         : no 
Enabled OpenDroneID                      : no 
Enabled firmware ID checking             : no 
GPS Debug Logging                        : no 
Enabled custom controller                : yes 
Checking for HAVE_CMATH_ISFINITE         : yes 
Checking for HAVE_CMATH_ISINF            : yes 
Checking for HAVE_CMATH_ISNAN            : yes 
Checking for NEED_CMATH_ISFINITE_STD_NAMESPACE : yes 
Checking for NEED_CMATH_ISINF_STD_NAMESPACE    : yes 
Checking for NEED_CMATH_ISNAN_STD_NAMESPACE    : yes 
Checking for header endian.h                   : yes 
Checking for header byteswap.h                 : yes 
Checking for HAVE_MEMRCHR                      : yes 
Configured VSCode Intellisense:                : no 
DC_DSDL compiler                               : /home/lck/mav_ws/ardupilot/modules/DroneCAN/dronecan_dsdlc/dronecan_dsdlc.py 
Source is git repository                       : yes 
Update submodules                              : yes 
Checking for program 'git'                     : /usr/bin/git 
Checking for program 'size'                    : /usr/bin/size 
Benchmarks                                     : disabled 
Unit tests                                     : enabled 
Scripting                                      : maybe 
Scripting runtime checks                       : enabled 
Debug build                                    : disabled 
Coverage build                                 : disabled 
Force 32-bit build                             : disabled 
Checking for program 'rsync'                   : /usr/bin/rsync 
'configure' finished successfully (2.711s)
{'model': 'JSON', 'sitl-port': True, 'waf_target': 'bin/arducopter'}
SIM_VEHICLE: Building
SIM_VEHICLE: "/home/lck/mav_ws/ardupilot/modules/waf/waf-light" "build" "--target" "bin/arducopter"
Waf: Entering directory `/home/lck/mav_ws/ardupilot/build/sitl'
Embedding file locations.txt:Tools/autotest/locations.txt
Embedding file models/BiCopter.json:Tools/autotest/models/BiCopter.json
Embedding file models/BiCopter.parm:Tools/autotest/models/BiCopter.parm
Embedding file models/Callisto.json:Tools/autotest/models/Callisto.json
Embedding file models/plane-3d.parm:Tools/autotest/models/plane-3d.parm
Embedding file models/plane.parm:Tools/autotest/models/plane.parm
Embedding file models/xplane_heli.json:Tools/autotest/models/xplane_heli.json
Embedding file models/xplane_plane.json:Tools/autotest/models/xplane_plane.json
Waf: Leaving directory `/home/lck/mav_ws/ardupilot/build/sitl'

BUILD SUMMARY
Build directory: /home/lck/mav_ws/ardupilot/build/sitl
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
----------------------------------------------------------------------------------------------------------
bin/arducopter   3960372    179165   215656               4139537  Not Applicable  Not Applicable         

Build commands will be stored in build/sitl/compile_commands.json
'build' finished successfully (5.505s)
The parameter file (/home/lck/ros_ws/src/bicopter_simulation/config/bicopter.param) does not exist
SIM_VEHICLE: Killing tasks

```

The Adupilot command window doesn't run like when executing IRIS or Zephyr, so which one should I add?

**Comment by srmainwaring** [comment]
> The parameter file (/home/lck/ros_ws/src/bicopter_simulation/config/bicopter.param) does not exist

Have you cloned this repo to `/home/lck/ros_ws/src/`? SITL can't find the parameter file, so exiting.

**Comment by GreenPine-CK** [comment]
I made a mistake on the route. I solved it.

**Comment by GreenPine-CK** [comment]
I've been doing a git clone and getting the file as it is, and I've checked it a few times and there's nothing wrong; 
I'm getting an error. How do I fix it?

**Comment by srmainwaring** [comment]
Look like a problem with you path. What does 

```bash
env | grep GZ
```

output?

**Comment by GreenPine-CK** [comment]
```
lck@aaa:~/gz_ws/src/bicopter_simulation/worlds$ gz sim -v4 -s -r bicopter_runway.sdf
[Msg] Gazebo Sim Server v7.6.0
[Msg] Loading SDF world file[/home/lck/gz_ws/src/bicopter_simulation/worlds/bicopter_runway.sdf].
[Msg] Serving entity system service on [/entity/system/add]
[Dbg] [Physics.cc:880] Loaded [gz::physics::dartsim::Plugin] from library [/usr/lib/x86_64-linux-gnu/gz-physics-6/engine-plugins/libgz-physics-dartsim-plugin.so]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Physics] for entity [1]
[Dbg] [Sensors.cc:506] Configuring Sensors system
[Dbg] [Sensors.cc:425] SensorsPrivate::Run
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Sensors] for entity [1]
SensorsPrivate::RenderThread started
[Dbg] [Sensors.cc:245] Waiting for init
[Msg] Create service on [/world/bicopter_runway/create]
[Msg] Remove service on [/world/bicopter_runway/remove]
[Msg] Pose service on [/world/bicopter_runway/set_pose]
[Msg] Pose service on [/world/bicopter_runway/set_pose_vector]
[Msg] Light configuration service on [/world/bicopter_runway/light_config]
[Msg] Physics service on [/world/bicopter_runway/set_physics]
[Msg] SphericalCoordinates service on [/world/bicopter_runway/set_spherical_coordinates]
[Msg] Enable collision service on [/world/bicopter_runway/enable_collision]
[Msg] Disable collision service on [/world/bicopter_runway/disable_collision]
[Msg] Material service on [/world/bicopter_runway/visual_config]
[Msg] Material service on [/world/bicopter_runway/wheel_slip]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::UserCommands] for entity [1]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::SceneBroadcaster] for entity [1]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Imu] for entity [1]
[Msg] ApplyJointForce subscribing to Double messages on [/model/bicopter_with_ardupilot/joint/bicopter::ccw_mot_joint/cmd_force]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::ApplyJointForce] for entity [18]
[Msg] ApplyJointForce subscribing to Double messages on [/model/bicopter_with_ardupilot/joint/bicopter::cw_mot_joint/cmd_force]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::ApplyJointForce] for entity [18]
[Msg] ApplyJointForce subscribing to Double messages on [/model/bicopter_with_ardupilot/joint/bicopter::ccw_servo_joint/cmd_force]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::ApplyJointForce] for entity [18]
[Msg] ApplyJointForce subscribing to Double messages on [/model/bicopter_with_ardupilot/joint/bicopter::cw_servo_joint/cmd_force]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::ApplyJointForce] for entity [18]
[Dbg] [SystemManager.cc:74] Loaded system [ArduPilotPlugin] for entity [18]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::JointStatePublisher] for entity [19]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [19]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [19]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [19]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [19]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [19]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [19]
[Msg] Loaded level [3]
[Msg] Serving world controls on [/world/bicopter_runway/control], [/world/bicopter_runway/control/state] and [/world/bicopter_runway/playback/control]
[Msg] Serving GUI information on [/world/bicopter_runway/gui/info]
[Msg] World [bicopter_runway] initialized with [1ms] physics profile.
[Msg] Serving world SDF generation service on [/world/bicopter_runway/generate_world_sdf]
[Msg] Serving world names on [/gazebo/worlds]
[Msg] Resource path add service on [/gazebo/resource_paths/add].
[Msg] Resource path get service on [/gazebo/resource_paths/get].
[Msg] Resource path resolve service on [/gazebo/resource_paths/resolve].
[Msg] Resource paths published on [/gazebo/resource_paths].
[Msg] Server control service on [/server_control].
[Wrn] [SimulationRunner.cc:676] Found additional publishers on /stats, using namespaced stats topic only
[Dbg] [SimulationRunner.cc:678] Publishers [Address, Message Type]:
[Dbg] [SimulationRunner.cc:683]   tcp://172.30.1.76:33083, gz.msgs.WorldStatistics
[Wrn] [SimulationRunner.cc:709] Found additional publishers on /clock, using namespaced clock topic only
[Dbg] [SimulationRunner.cc:711] Publishers [Address, Message Type]:
[Dbg] [SimulationRunner.cc:716]   tcp://172.30.1.76:33083, gz.msgs.Clock
[Dbg] [SimulationRunner.cc:503] Creating PostUpdate worker threads: 6
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (0)
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (1)
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (2)
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (3)
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (4)
[Msg] Found IMU sensor with name [bicopter::imu_link::imu_sensor]
[Dbg] [ArduPilotPlugin.cc:1154] Computed IMU topic to be: world/bicopter_runway/model/bicopter_with_ardupilot/model/bicopter/link/imu_link/sensor/imu_sensor/imu
[Dbg] [SDFFeatures.cc:328] Mesh construction from an SDF has not been implemented yet for dartsim. Use AttachMeshShapeFeature to use mesh shapes.
[Err] [SDFFeatures.cc:843] The geometry element of collision [collision] couldn't be created
[Dbg] [SDFFeatures.cc:328] Mesh construction from an SDF has not been implemented yet for dartsim. Use AttachMeshShapeFeature to use mesh shapes.
[Err] [SDFFeatures.cc:843] The geometry element of collision [collision] couldn't be created
[Dbg] [SDFFeatures.cc:328] Mesh construction from an SDF has not been implemented yet for dartsim. Use AttachMeshShapeFeature to use mesh shapes.
[Err] [SDFFeatures.cc:843] The geometry element of collision [collision] couldn't be created
[Dbg] [SDFFeatures.cc:328] Mesh construction from an SDF has not been implemented yet for dartsim. Use AttachMeshShapeFeature to use mesh shapes.
[Err] [SDFFeatures.cc:843] The geometry element of collision [collision] couldn't be created
[Dbg] [SDFFeatures.cc:328] Mesh construction from an SDF has not been implemented yet for dartsim. Use AttachMeshShapeFeature to use mesh shapes.
[Err] [SDFFeatures.cc:843] The geometry element of collision [collision] couldn't be created
[Dbg] [ImuSensor.cc:149] IMU data for [bicopter_with_ardupilot::bicopter::imu_link::imu_sensor] advertised on [world/bicopter_runway/model/bicopter_with_ardupilot/model/bicopter/link/imu_link/sensor/imu_sensor/imu]
[Msg] Serving scene information on [/world/bicopter_runway/scene/info]
[Msg] Serving graph information on [/world/bicopter_runway/scene/graph]
[Msg] Serving full state on [/world/bicopter_runway/state]
[Msg] Serving full state (async) on [/world/bicopter_runway/state_async]
[Msg] Publishing scene information on [/world/bicopter_runway/scene/info]
[Msg] Publishing entity deletions on [/world/bicopter_runway/scene/deletion]
[Msg] Publishing state changes on [/world/bicopter_runway/state]
[Msg] Publishing pose messages on [/world/bicopter_runway/pose/info]
[Msg] Publishing dynamic pose messages on [/world/bicopter_runway/dynamic_pose/info]

```

**Comment by GreenPine-CK** [comment]
> Look like a problem with you path. What does
> 
> ```shell
> env | grep GZ
> ```
> 
> output?


```
lck@aaa:~/gz_ws/src/bicopter_simulation/worlds$ env | grep GZ
GZ_SIM_RESOURCE_PATH=/home/lck/gz_ws/src/ardupilot_gazebo/models:/home/lck/gz_ws/src/ardupilot_gazebo/worlds:/home/lck/gz_ws/src/ardupilot_gazebo/models:/home/lck/gz_ws/src/ardupilot_gazebo/worlds:/home/lck/gz_ws/src/ardupilot_gazebo/models:/home/lck/gz_ws/src/ardupilot_gazebo/worlds:/home/lck/gz_ws/src/ardupilot_gazebo/models:/home/lck/gz_ws/src/ardupilot_gazebo/worlds:/home/lck/gz_ws/src/ardupilot_gazebo/models:/home/lck/gz_ws/src/ardupilot_gazebo/worlds:/home/lck/gz_ws/src/ardupilot_gazebo/models:/home/lck/gz_ws/src/ardupilot_gazebo/worlds:/home/lck/gz_ws/src/ardupilot_gazebo/models:/home/lck/gz_ws/src/ardupilot_gazebo/worlds::/home/lck/gz_ws/src/ardupilot_gazebo/models:/home/lck/gz_ws/src/ardupilot_gazebo/worlds:/home/lck/gz_ws/src/bicopter_simulation/models:/home/lck/gz_ws/src/bicopter_simulation/worlds
GZ_SIM_SYSTEM_PLUGIN_PATH=/home/lck/gz_ws/src/ardupilot_gazebo/build:/home/lck/gz_ws/src/ardupilot_gazebo/build:/home/lck/gz_ws/src/ardupilot_gazebo/build:/home/lck/gz_ws/src/ardupilot_gazebo/build:/home/lck/gz_ws/src/ardupilot_gazebo/build:/home/lck/gz_ws/src/ardupilot_gazebo/build:/home/lck/gz_ws/src/ardupilot_gazebo/build::/home/lck/gz_ws/src/ardupilot_gazebo/build

```

**Comment by srmainwaring** [comment]
The model file appears to be in the GZ_SIM_RESOURCE_PATH, although you have many repeats. A clean terminal should only have each entry once.

The last log seems to show the model being loaded, is it appearing in the Gazebo GUI?

**Comment by GreenPine-CK** [comment]
Screenshot from 2023-12-15 00-29-34

I erased the recurring old PATH.

**Comment by GreenPine-CK** [comment]
> The model file appears to be in the GZ_SIM_RESOURCE_PATH, although you have many repeats. A clean terminal should only have each entry once.
> 
> The last log seems to show the model being loaded, is it appearing in the Gazebo GUI?

GAZEBO GUI will not run.

**Comment by GreenPine-CK** [comment]
'gz sim -v4 -s -r bicopter_runway.sdf' The console program runs, 
but 'gazebo-gui' doesn't work, 
and when you run 'gz sim -v4 bicopter_runway.sdf', the GUI works, 
but it doesn't connect to simvehicle.py.

 'gz sim -v4 -r bicopter_runway.sdf' connects GUI and simvehicle.py to operation.

Why?

**Comment by GreenPine-CK** [comment]
Thank you very much.
I succeeded in flying

It's so nice how I can repay you.

2023년 12월 15일 (금) 오전 12:24, Rhys Mainwaring ***@***.***>님이 작성:

**Comment by srmainwaring** [comment]
> Thank you very much. I succeeded in flying

Amazing! Glad you managed to get the model running.

Do you have parameters for a stable tune? I'm still trying to get the bicopter to hover well - it's almost there but very noisy at the moment.

**Comment by srmainwaring** [comment]
> 'gz sim -v4 -s -r bicopter_runway.sdf' The console program runs,
> but 'gazebo-gui' doesn't work,

Ah yes, my mistake. I develop on macOS where you need to start the GUI and server separately (so -s for one and -g for the other), on Ubuntu you run a single command.

**Comment by GreenPine-CK** [comment]
> > Thank you very much. I succeeded in flying
> 
> Amazing! Glad you managed to get the model running.
> 
> Do you have parameters for a stable tune? I'm still trying to get the bicopter to hover well - it's almost there but very noisy at the moment.

Unfortunately, Bicopter is a shape that I've only made in my imagination, so I don't know the PID value for stable flight. It's safe to say that we made this simulation to design such a PID GAIN or controller. I'll also look for gain values to make it a stable flight.

**Comment by GreenPine-CK** [comment]
I have one more question. I'm developing in Ubuntu environment with a very low spec pc. So it's very hard to run 'runway world'. Is there any way to run it on wireframe except for runway in world file?

**Comment by srmainwaring** [comment]
> Unfortunately, Bicopter is a shape that I've only made in my imagination, so I don't know the PID value for stable flight. It's safe to say that we made this simulation to design such a PID GAIN or controller. I'll also look for gain values to make it a stable flight.

ArduPilot has support for bicopters (although there is not too much by the way of documentation for tuning them). This last PR contains an ArduPilot parameter set and tweak of the model parameters that enables autonomous flight.

- https://github.com/GreenPine-CK/bicopter_simulation/pull/5

**Comment by srmainwaring** [comment]
> I have one more question. I'm developing in Ubuntu environment with a very low spec pc. So it's very hard to run 'runway world'. Is there any way to run it on wireframe except for runway in world file?

You can run a simple ground plane (the `shapes.sdf` world example has a groundplane you can use), however I suspect the computational expense is running the physics for the model ArduPilot SITL backend rather than the rendering (if you run the server only this will give you some idea). If the rendering is the issue you can configure Gazebo GUI to use the ogre rather than ogre2 render engine. The Gazebo Sim docs online should have more information about this.

**Pull request merged**
